### ISSUE TITLE
Problem med Forcering vid låga gradminuter men nya funktionen på 20htz

### ISSUE THREAD

**Issue by doe81** [anerdins/node-red-contrib-nibepi#7]
Testade igår 1.2.1 primärt för att få bättre automatiskt luftflöde.
Märkte ganska snabbt att "Forcering vid låga gradminuter" fungerar inge bra med ny funktionen med låsning vid högt pris på 20Hz.
Gick från normalt till dyrt pris och med låga GM så "Forcering vid låga gradminuter" var aktiverat. Och då nya funktionen inte återställer GM och istället låser. Vilket resulterar i att kompressorn får på 20Hz och men låga GM och aktiv "Forcering vid låga gradminuter".

Bör vara en koll på forceringen att inte låsningen är aktiv. Annars är det onödigt att ventilera så mycket om man ändå bara ska köra kompressorn i 20Hz.

**Comment by anerdins** [comment]
Tack, bra info Den 8 dec. 2022 19:03 skrev doe81 ***@***.***>:

Testade igår 1.2.1 primärt för att få bättre automatiskt luftflöde.

Märkte ganska snabbt att "Forcering vid låga gradminuter" fungerar inge bra med ny funktionen med låsning vid högt pris på 20Hz.

Gick från normalt till dyt pris och med låga GM så "Forcering vid låga gradminuter" var aktiverat. Och då nya funktionen inte återställer GM och istället låster. Vilket resulterar i att kompressorn får på 20Hz och men låga GM och aktiv "Forcering vid låga gradminuter".

Bör vara en koll på forceringen att inte låsningen är aktiv. Annars är det onödigt att ventilera så mycket om man ändå bara ska köra kompressorn i 20Hz.

**Comment by anerdins** [comment]
Jag har uppdaterat 1.2.1 med en eventuell fix!
